apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-list
  namespace: pi-hole
  labels:
    app: pi-hole
data:
  03-pihole-custom-dns.conf: |
    address=/prometheus.sac23.io/192.168.178.200
    address=/grafana.sac23.io/192.168.178.200
  pihole-FTL.conf: |
    #; Pi-hole FTL config file
    #; Comments should start with #; to avoid issues with PHP and bash reading this file
    PRIVACYLEVEL=0
    RATE_LIMIT=0/0
  setupVars.conf: |
    PIHOLE_INTERFACE=eth0
    IPV4_ADDRESS=0.0.0.0
    IPV6_ADDRESS=0:0:0:0:0:0
    QUERY_LOGGING=true
    INSTALL_WEB_SERVER=true
    INSTALL_WEB_INTERFACE=true
    LIGHTTPD_ENABLED=true
    CACHE_SIZE=10000
    DNS_FQDN_REQUIRED=true
    DNS_BOGUS_PRIV=true
    DNSMASQ_LISTENING=local
    BLOCKING_ENABLED=true
    PIHOLE_DNS_1=8.8.8.8
    DNSSEC=false
    REV_SERVER=false
