apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
      - name: pi-hole
        image: pihole/pihole
        ports:
        - containerPort: 53
        - containerPort: 80
        env:
        - name: TZ
          value: 'Europe/London'
        - name: WEBPASSWORD
          value: Pizzaman7
        - name: DNSMASQ_LISTENING
          value: all
#        volumeMounts:
#        - name: custom-list
#          mountPath: /etc/pihole/
#      volumes:
#      - name: custom-list
#        configMap:
#          name: custom-list
#          items:
#          - key: custom.list
#            path: custom.list

  
