apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
      - name: pi-hole
        image: pihole/pihole:2023.05.2
        ports:
        - containerPort: 53
        - containerPort: 80
        env:
        - name: TZ
          value: 'Europe/London'
        - name: WEBPASSWORD
          value: Pizzaman7
        - name: DNSMASQ_LISTENING
          value: all
        volumeMounts:
        - name: custom-list
          mountPath: /etc/dnsmasq.d/
        - name: pihole-ftl
          mountPath: /etc/pihole/
      volumes:
      - name: pihole-ftl
        configMap:
          name: custom-list
          items:
          - key: pihole-FTL.conf
            path: pihole-FTL.conf
          - key: setupVars.conf
            path: setupVars.conf
          - key: dns-servers.conf
            path: dns-servers.conf
      - name: custom-list
        configMap:
          name: custom-list
          items:
          - key: 03-pihole-custom-dns.conf
            path: 03-pihole-custom-dns.conf

  
