apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../../collection/pihole
    - ../../collection/prometheus
    - ../../collection/kube-state-metrics
    - ../../collection/cert-manager
