apiVersion: v1
kind: Service
metadata:
  name: pi-hole-service
  namespace: pi-hole
  labels:
    name: pi-hole-service
spec:
  selector:
    app: pi-hole
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: "tcp53"
    - protocol: UDP
      port: 53
      targetPort: 53      
      name: "udp53"
    - port: 8080
      targetPort: 80
      name: "tcp8080"
  type: LoadBalancer
