---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-files-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:8.5.22
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
            name: http-grafana
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-files
            readOnly: false
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
      - name: grafana-files
        persistentVolumeClaim: 
        claimName: grafana-storage
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
